version: '3.8'

services:
  postgres:
    container_name: postgres-keycloak
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      keycloak-network:
        ipv4_address: 172.20.0.2

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.2.4
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command:
      - start-dev
      - --import-realm
    ports:
      - 8080:8080
    depends_on:
      - postgres
    volumes:
      - ./keycloak-config/uems-realm-realm.json:/opt/keycloak/data/import/uems-realm-realm.json
    networks:
      keycloak-network:
        ipv4_address: 172.20.0.3

  grafana:
    container_name: grafana-keycloak
    image: grafana/grafana:12.0.0
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
      GF_AUTH_GENERIC_OAUTH_NAME: "UEMS"
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: "true"
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ${GRAFANA_OAUTH_CLIENT_ID}
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ${GRAFANA_OAUTH_CLIENT_SECRET}
      GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email roles"
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: "http://172.20.0.3:8080/realms/uems-realm/protocol/openid-connect/auth"
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "http://172.20.0.3:8080/realms/uems-realm/protocol/openid-connect/token"
      GF_AUTH_GENERIC_OAUTH_API_URL: "http://172.20.0.3:8080/realms/uems-realm/protocol/openid-connect/userinfo"
      GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(roles[*], 'GrafanaAdmin') && 'GrafanaAdmin' || contains(roles[*], 'Admin') && 'Admin' || contains(roles[*], 'Editor') && 'Editor' || 'Viewer'"
      GF_AUTH_GENERIC_OAUTH_ALLOW_ASSIGN_GRAFANA_ADMIN: "true"
      GF_AUTH_GENERIC_OAUTH_SIGNOUT_REDIRECT_URL: "http://172.20.0.3:8080/realms/uems-realm/protocol/openid-connect/logout?post_logout_redirect_uri=http://172.20.0.4:3000/login"
      GF_SERVER_ROOT_URL: "http://172.20.0.4:3000"
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - keycloak
    networks:
      keycloak-network:
        ipv4_address: 172.20.0.4

volumes:
  postgres_data:
  grafana_data:

networks:
  keycloak-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24